config/routes.rb
Rails.application.routes.draw do

 

  resources :sessions, only: [:new, :create, :destroy]

  
  
  resources :tenants
  resources :agents
  resources :property_managers
  resources :system_users
  resources :deposits
  resources :apartments
  resources :properties
  resources :tickets
  resources :application_fees
  resources :rents
  resources :payments
  resources :appointments
  

  

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  get 'static_pages', to: 'static_pages#home'
  get 'property_managers_home', to: 'static_pages#property_managers_home', as: 'property_managers_home'
  get 'properties_home', to: 'staticpages#properties_home', as: 'properties_home'
  get 'tenants_home', to: 'static_pages#tenants_home', as: 'tenants_home'
  get 'agents_home', to: 'static_pages#agents_home', as: 'agents_home'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'about', to: 'static_pages#about', as: 'about'

  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def contact
  end
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_left_navbar.html.erb
<div>
  <% if current_user %>
    <p> Hello <%= link_to current_user.firstname, session_home  %>!</p>
    <P>
      <%= link_to 'Profile', current_user %>

    </p>
  <% end %>
  <% if current_user && current_user.type == admin %>
    <p><%= link_to 'View tenants', tenants_path  %></p>
    <p><%= link_to 'View agents', agents_path  %></p>
    <p><%= link_to 'View tickets', tickets_path  %></p>
    <p><%= link_to 'Issue ticket', new_ticket_path  %></p>
    <p><%= link_to 'View Properties', properties_path  %></p>
    
    <p><%= link_to 'View apartments', apartments_path %></p>

    <p><%= link_to 'Create user', new_system_user_path  %></p>
    <!--<p><%= link_to 'Create manager', new_property_manager_path  %></p>-->
    
    <p><%= link_to 'View appointments', appointments_path  %></p>
    
  <% elsif current_user && current_user.type == maintenance %>

    <p><%= link_to 'View tickets', tickets_path  %></p>

  <% elsif current_user && current_user.type == resident%>
    <p><%= link_to 'Issue ticket', new_ticket_path  %></p>
    <p><%= link_to 'View payments', payments_path  %></p>
    <p><%= link_to 'View tickets', tickets_path  %></p>

  <%else %>
  <% end %>
</div>

app/views/static_pages/_right_navbar.html.erb
<% count = count_my_active_tickets(current_user)%>
<div class="well">
	<% if count %>
  <p><%= count_my_active_tickets(current_user) %> New tickets</p>
  <% end %>
</div>
<div class="well">
	<p>ADS</p>
</div>

app/views/static_pages/_top_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>

      <a class="navbar-brand" href=<%= root_path %>>ADGK-Property</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li class="active"><%= link_to "View Properties", properties_path %></li>
        <li>
        <%= link_to 'Request an appointment', new_appointment_path %> </li>
        <li class="active"><%= link_to "Contact", contact_path %></li>
        <li class="active"><%= link_to "About", about_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><% if current_user %>
				<%= link_to 'Log Out', logout_path %>
	 		<% else %>
 				<%= link_to 'Log In', login_path %>
 			<% end %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/static_pages/about.html.erb
<h1>ADGK-Property in Mt. Everest</h1>
<body>
	<p>Hello and welcome to the Fantasy apartments in Mt. Everest! We have different units available for rent with reasonable prices.<br>
	The apartments are located at the top of the world. You will have an opportunity to enjoy the freezing environment and also <br>
	you will get chance to experience how it feels in the altitude where there is oxygen deficiency. This could be the right<br> apartment if you are a nature lover.
	</p>
	<div>
		<h4>Features:</h4>
		
		<p>
		Low price apartments in the town
		<p>
		Free internet facility
		<p>
		Free maintainance and repair service in case of damage
		<p>
		Famous for sunrise view

		</p>
	</div>
</body>

app/views/static_pages/agents_home.html.erb
<h1>Agents Home</h1>
	<div>
		<ul>
		  <li><%= link_to 'View profile', agents_path  %></li>
		  <li><%= link_to 'View tickets', tickets_path  %></li>
		</ul>
	</div>

	<!--
	<div class="col-lg-12">
        <div class="panel panel-success">
            <div class="panel-heading">Tickets</div>
            <div class="panel-body">
                <p>tickets list</p>
            </div>
            <div class="panel-footer">
            	View ticket history
            </div>
        </div>
    </div>
    -->

app/views/static_pages/contact.html.erb
<h1>ADGK-Property in Mt. Everest</h1>
<body>
	<p>
		<h4>OUR LOCATION</h4><br>
	ADGK Properties 
	<p> 	
	Mynder Ave
	<p> Memphis, TN,38111 <br>
	<p>
	Phone: 901.678.0011<br>
	<p>
	Email: admin@adgk.com
	</p>

	<p>
	<h4>IMPORTANT NUMBERS</h4><br>
	<p> 
	Rent Payment: 901.678.0012
	<p>
	Maintainance Service: 901.678. 0013
	<p>
	Parking Ticket: 901.678.0014
	</p>
</body> 

app/views/static_pages/home.html.erb
<h1>ADGK-Property in Mt. Everest</h1>
<body>
	<p>Hello and welcome to the Fantasy apartments in Mt. Everest! We have different units available for rent with reasonable prices.<br>
	The apartments are located at the top of the world. You will have an opportunity to enjoy the freezing environment and also <br>
	you will get chance to experience how it feels in the altitude where there is oxygen deficiency. This could be the right<br> apartment if you are a nature lover.
	</p>
	<div>
		


		<img src="/assets/apts.jpg"  />
		<div>&nbsp;</div>
		<img src="/assets/mteverest.jpg"  />
		<p>
			sources:
			<ul>
			  <li><a href="https://www.flickr.com/photos/atdisneyagain/11638843044/in/photolist-iJu7xE-7j8pEb-dgB8HY-gvMBq-edAmvj-diNTD6-eduDRZ-nqWCyr-5AbxVn-8t63Wr-aSqQdM-c54abE-88ohNF-hbLQwi-bV2KnD-mnihgT-b3m4LT-nExLhh-bhWSFV-qJwHtB-qpZLod-r8xvYw-qJajh7-4L7SML-e25Sj7-oY2n7t-5MigiW-auWJGu-et8AuP-q7tyQx-pua2XN-4Ba3nE-nkqLwd-2PDUgN-8rkEQV-qqSQAH-7iZ9R6-9XYXpD-qNmRoa-c9Hz17-8caeiy-c9HyLL-pjNdrs-jiW1ps-diNKNE-mnj1c4-dSdZkw-nASqqb-qKSPrV-pvt7yy">atdisneyagain</a></li>
			  <li><a href="https://www.flickr.com/photos/trebbyeah/6866928229/in/photolist-bsNNwi-7PeRG9-4xMLeh-b3VLdT-ftBg9-7CzwNg-4xHCxr-4xHCRV-7xfbRk-5Yxi3y-4xHyUt-4xMQGs-dYsENy-7uico1-7GVJ2d-q8YGVX-q7e7pT-4Fmspb-nLfn3H-6XDv6E-4FmtXs-b3VLFc-7PaRRR-BEMzs-bz8STv-4FmtzU-4xj55E-4xMQMU-7PeRyA-4dQmu5-dYmY1Z-67S4H9-5TqUq4-4xiTgh-qtCEoQ-9zD2jE-67MDoX-4xMPYE-fwmD2P-BEGs8-4AZBXK-A8VkT-4xHDji-7Af4V6-4xj5Po-bme3mw-4xiVvG-qFJPZ5-bmecqd-b3VNCF">trebbyeah</a></li>
			  <li><a href="https://www.flickr.com/photos/unioz/17971020624/in/photolist-nWGcgC-nEjHrW-nWPaZD-nWPbKX-nWPbAD-nWvTyH-nWP9a6-aVd8KF-aDK2N1-dvLW8z-8cE3sk-4GFhpQ-Mn17Z-7m6UMu-moMJ39-to3bkb-MmUeA-8yA5e9-MmjBD-MmigR-MmKeY-nWNYix-dUREUk-nWPdcz-boGas9-nEjDYo-nEkwyt-bzMxDn-nEiygn-nWHkwq-bC9HZk-nULr6E-aVd8En-nEiwCb-nEjHHN-nEjjPa-nEjmZx-2H5GsA-nWuVfv-nEjHds-FmeJh-nEjQmY-2H22hr-FmkUQ-bBB4ot-nWvXvv-aVd97D-5LQF4Q-Fmaep-bmSKHY/">unioz</a></li>
			</ul>
		</p>
	</div>
</body>

app/views/static_pages/property_managers_home.html.erb
<h1>Manager Home</h1>
<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-success">

            <div class="panel-heading">Properties</div>

            <div class="panel-body">
                <p>By clicking the link, you can view and edit the properties</p>
            </div>
            <div class="panel-footer">
                <%= link_to 'More', properties_path  %>
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <div class="panel panel-success">
            <div class="panel-heading">Tenants</div>

            <div class="panel-body">
                <p>By clicking the link, you can view and edit the tenants</p>
            </div>
            <div class="panel-footer">
                <%= link_to 'More', tenants_path  %>
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <div class="panel panel-success">
            <div class="panel-heading">Agents</div>
            <div class="panel-body">
                <p>By clicking the link, you can view and edit the agents</p>
            </div>
            <div class="panel-footer">
                <%= link_to 'More', agents_path  %>
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
</div>

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-success">
            <div class="panel-heading">View profile</div>
            <div class="panel-body">
                <p>By clicking the link, you can view and edit the property managers</p>
            </div>
            <div class="panel-footer">
                <%= link_to 'More', current_user  %>
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <div class="panel panel-success">
            <div class="panel-heading">Create new:</div>
            <div class="panel-body">
                <p><%= link_to 'Property manager', new_property_manager_path  %></p>
                <p><%= link_to 'Tenant', new_tenant_path  %></p>
                <p><%= link_to 'Agent', new_agent_path  %></p>
            </div>
            <div class="panel-footer">
                
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <div class="panel panel-success">
            <div class="panel-heading">View tickets</div>

            <div class="panel-body">
                <p>By clicking the link, you can view and edit the tickets</p>
            </div>
            <div class="panel-footer">
                <%= link_to 'Click here', tickets_path  %>
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
</div>

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-success">
            <div class="panel-heading">View Requested Appointments</div>
            <div class="panel-body">
                <p>By clicking the link, you can view and edit the appointments</p>
            </div>
            <div class="panel-footer">
                <%= link_to 'View', appointments_path  %>
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
</div>

app/views/static_pages/tenants_home.html.erb
<h1>Tenants home</h1>
<body>
	<div>
		<ul>
		  <li><%= link_to 'View profile', tenants_path  %></li>
		  <li><%= link_to 'View payments', payments_path  %></li>
		  <li><%= link_to 'View tickets', tickets_path  %></li>
		</ul>
	</div>
</body>