config/routes.rb
Rails.application.routes.draw do

 

  resources :sessions, only: [:new, :create, :destroy]

  
  
  resources :tenants
  resources :agents
  resources :property_managers
  resources :system_users
  resources :deposits
  resources :apartments
  resources :properties
  resources :tickets
  resources :application_fees
  resources :rents
  resources :payments
  resources :appointments
  

  

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  get 'static_pages', to: 'static_pages#home'
  get 'property_managers_home', to: 'static_pages#property_managers_home', as: 'property_managers_home'
  get 'properties_home', to: 'staticpages#properties_home', as: 'properties_home'
  get 'tenants_home', to: 'static_pages#tenants_home', as: 'tenants_home'
  get 'agents_home', to: 'static_pages#agents_home', as: 'agents_home'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'about', to: 'static_pages#about', as: 'about'

  root to: 'static_pages#home'

end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id                 :integer          not null, primary key
#  propertyname       :string
#  propertyaddress    :string
#  propertyowner      :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  PropertyManager_id :integer
#


class Property < ActiveRecord::Base
	belongs_to :property_manager, class_name: "PrpopertyManager", foreign_key: "property_manager_id"
	has_many   :apartments, class_name: "Apartment", foreign_key: "property_id"
	validates  :propertyname, length: {maximum: 250 } , presence:true
	validates  :propertyaddress, length: {maximum: 250} , presence:true
	validates  :propertyowner, length: {maximum: 250} , presence:true 

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:propertyname, :propertyaddress, :propertyowner, :property_manager_id)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :propertyname %><br>
    <%= f.text_field :propertyname %>
  </div>
  <div class="field">
    <%= f.label :propertyaddress %><br>
    <%= f.text_field :propertyaddress %>
  </div>
  <div class="field">
    <%= f.label :propertyowner %><br>
    <%= f.text_field :propertyowner %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Propertyname</th>
      <th>Propertyaddress</th>
      <th>Propertyowner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.propertyname %></td>
        <td><%= property.propertyaddress %></td>
        <td><%= property.propertyowner %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Propertyname:</strong>
  <%= @property.propertyname %>
</p>

<p>
  <strong>Propertyaddress:</strong>
  <%= @property.propertyaddress %>
</p>

<p>
  <strong>Propertyowner:</strong>
  <%= @property.propertyowner %>
</p>
<hr>
<h1>Listing Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Apartmentnumber</th>
      <th>Apartmenttype</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
    <% @property.apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.apartmentnumber %></td>
        <td><%= apartment.apartmenttype %></td>
        <td><%= apartment.status %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  <br>
<%= link_to 'New Apartment', new_apartment_path %>

<hr>
<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>