config/routes.rb
Rails.application.routes.draw do

 

  resources :sessions, only: [:new, :create, :destroy]

  
  
  resources :tenants
  resources :agents
  resources :property_managers
  resources :system_users
  resources :deposits
  resources :apartments
  resources :properties
  resources :tickets
  resources :application_fees
  resources :rents
  resources :payments
  resources :appointments
  

  

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  get 'static_pages', to: 'static_pages#home'
  get 'property_managers_home', to: 'static_pages#property_managers_home', as: 'property_managers_home'
  get 'properties_home', to: 'staticpages#properties_home', as: 'properties_home'
  get 'tenants_home', to: 'static_pages#tenants_home', as: 'tenants_home'
  get 'agents_home', to: 'static_pages#agents_home', as: 'agents_home'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'about', to: 'static_pages#about', as: 'about'

  root to: 'static_pages#home'

end

app/models/application_fee.rb
# == Schema Information
#
# Table name: payments
#
#  id            :integer          not null, primary key
#  amount        :float
#  type          :string
#  paymentdate   :date
#  paymentstatus :boolean
#  duemonth      :string
#  comment       :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  apartment_id  :integer
#  tenant_id     :integer
#


class ApplicationFee < Payment

	belongs_to :tenant, class_name: "Tenant"
end

app/controllers/application_fees_controller.rb
class ApplicationFeesController < ApplicationController
  before_action :set_application_fee, only: [:show, :edit, :update, :destroy]

  # GET /application_fees
  # GET /application_fees.json
  def index
    @application_fees = ApplicationFee.all
  end

  # GET /application_fees/1
  # GET /application_fees/1.json
  def show
  end

  # GET /application_fees/new
  def new
    @application_fee = ApplicationFee.new
  end

  # GET /application_fees/1/edit
  def edit
  end

  # POST /application_fees
  # POST /application_fees.json
  def create
    @application_fee = ApplicationFee.new(application_fee_params)

    respond_to do |format|
      if @application_fee.save
        format.html { redirect_to @application_fee, notice: 'Application fee was successfully created.' }
        format.json { render :show, status: :created, location: @application_fee }
      else
        format.html { render :new }
        format.json { render json: @application_fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_fees/1
  # PATCH/PUT /application_fees/1.json
  def update
    respond_to do |format|
      if @application_fee.update(application_fee_params)
        format.html { redirect_to @application_fee, notice: 'Application fee was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_fee }
      else
        format.html { render :edit }
        format.json { render json: @application_fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_fees/1
  # DELETE /application_fees/1.json
  def destroy
    @application_fee.destroy
    respond_to do |format|
      format.html { redirect_to application_fees_url, notice: 'Application fee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_fee
      @application_fee = ApplicationFee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_fee_params
      params.fetch(:application_fee, {})
    end
end

app/helpers/application_fees_helper.rb
module ApplicationFeesHelper
end

app/views/application_fees/_form.html.erb
<%= form_for(@application_fee) do |f| %>
  <% if @application_fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application_fee.errors.count, "error") %> prohibited this application_fee from being saved:</h2>

      <ul>
      <% @application_fee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/application_fees/edit.html.erb
<h1>Editing Application Fee</h1>

<%= render 'form' %>

<%= link_to 'Show', @application_fee %> |
<%= link_to 'Back', application_fees_path %>

app/views/application_fees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Application Fees</h1>

<table class='table'>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application_fees.each do |application_fee| %>
      <tr>
        <td><%= link_to 'Show', application_fee %></td>
        <td><%= link_to 'Edit', edit_application_fee_path(application_fee) %></td>
        <td><%= link_to 'Destroy', application_fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application fee', new_application_fee_path %>

app/views/application_fees/new.html.erb
<h1>New Application Fee</h1>

<%= render 'form' %>

<%= link_to 'Back', application_fees_path %>

app/views/application_fees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_application_fee_path(@application_fee) %> |
<%= link_to 'Back', application_fees_path %>