config/routes.rb
Rails.application.routes.draw do

 

  resources :sessions, only: [:new, :create, :destroy]

  
  
  resources :tenants
  resources :agents
  resources :property_managers
  resources :system_users
  resources :deposits
  resources :apartments
  resources :properties
  resources :tickets
  resources :application_fees
  resources :rents
  resources :payments
  resources :appointments
  

  

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  get 'static_pages', to: 'static_pages#home'
  get 'property_managers_home', to: 'static_pages#property_managers_home', as: 'property_managers_home'
  get 'properties_home', to: 'staticpages#properties_home', as: 'properties_home'
  get 'tenants_home', to: 'static_pages#tenants_home', as: 'tenants_home'
  get 'agents_home', to: 'static_pages#agents_home', as: 'agents_home'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'about', to: 'static_pages#about', as: 'about'

  root to: 'static_pages#home'

end

app/models/deposit.rb
# == Schema Information
#
# Table name: payments
#
#  id            :integer          not null, primary key
#  amount        :float
#  type          :string
#  paymentdate   :date
#  paymentstatus :boolean
#  duemonth      :string
#  comment       :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  apartment_id  :integer
#  tenant_id     :integer
#


class Deposit < Payment
	belongs_to :tenant, class_name: "Tenant"
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_deposit, only: [:show, :edit, :update, :destroy]

  # GET /deposits
  # GET /deposits.json
  def index
    @deposits = Deposit.all
  end

  # GET /deposits/1
  # GET /deposits/1.json
  def show
  end

  # GET /deposits/new
  def new
    @deposit = Deposit.new
  end

  # GET /deposits/1/edit
  def edit
  end

  # POST /deposits
  # POST /deposits.json
  def create
    @deposit = Deposit.new(deposit_params)

    respond_to do |format|
      if @deposit.save
        format.html { redirect_to @deposit, notice: 'Deposit was successfully created.' }
        format.json { render :show, status: :created, location: @deposit }
      else
        format.html { render :new }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deposits/1
  # PATCH/PUT /deposits/1.json
  def update
    respond_to do |format|
      if @deposit.update(deposit_params)
        format.html { redirect_to @deposit, notice: 'Deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit }
      else
        format.html { render :edit }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposits/1
  # DELETE /deposits/1.json
  def destroy
    @deposit.destroy
    respond_to do |format|
      format.html { redirect_to deposits_url, notice: 'Deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposit
      @deposit = Deposit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deposit_params
      params.fetch(:deposit, {})
    end
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/_form.html.erb
<%= form_for(@deposit) do |f| %>
  <% if @deposit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposit.errors.count, "error") %> prohibited this deposit from being saved:</h2>

      <ul>
      <% @deposit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deposits/edit.html.erb
<h1>Editing Deposit</h1>

<%= render 'form' %>

<%= link_to 'Show', @deposit %> |
<%= link_to 'Back', deposits_path %>

app/views/deposits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deposits</h1>

<table class='table'>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= link_to 'Show', deposit %></td>
        <td><%= link_to 'Edit', edit_deposit_path(deposit) %></td>
        <td><%= link_to 'Destroy', deposit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposit', new_deposit_path %>

app/views/deposits/new.html.erb
<h1>New Deposit</h1>

<%= render 'form' %>

<%= link_to 'Back', deposits_path %>

app/views/deposits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_deposit_path(@deposit) %> |
<%= link_to 'Back', deposits_path %>